[package]
name = "clamav-client"
version = "0.3.2"
authors = ["Thorsten Blum"]
edition = "2021"
homepage = "https://github.com/toblux/rust-clamav-client"
repository = "https://github.com/toblux/rust-clamav-client"
description = "ClamAV client library"
readme = "README.md"
license = "MIT"
keywords = ["clamav", "clamd", "anitvirus", "async"]

[dependencies]
tokio = { version = "1.34.0", features = ["fs", "io-util", "net"], optional = true }

[dev-dependencies]
tokio = { version = "1.34.0", features = ["io-std", "macros", "rt"] }

[features]
tokio = ["dep:tokio"]

[package.metadata.docs.rs]
features = ["tokio"]
